service: security-group-service
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.serverlessStage}
  region: ap-southeast-2
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:DescribeSecurityGroups
      Resource: '*'

functions:
  app:
    handler: src/api.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
          authorizer: authorizerFunc
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
          authorizer: authorizerFunc
  authorizerFunc:
    handler: src/api.authorizer

custom:
  serverlessStage: ${opt:stage, 'dev'}